version: "3.8"

volumes:
  home_node_modules:
  issuer_node_modules:
  redeemer_node_modules:

services:
  home:
    build: ./services/home
    container_name: "home"
    env_file:
      - .env
    volumes:
      - ./services/home:/workspace
      - home_node_modules:/workspace/node_modules
    networks:
      - internal

  issuer:
    build: ./services/issuer
    container_name: "issuer"
    env_file:
      - .env
    volumes:
      - ./services/issuer:/workspace
      - issuer_node_modules:/workspace/node_modules
    networks:
      - internal

  redeemer:
    build: ./services/redeemer
    container_name: "redeemer"
    env_file:
      - .env
    volumes:
      - ./services/redeemer:/workspace
      - redeemer_node_modules:/workspace/node_modules
    networks:
      - internal

  nginx:
    image: nginx:1.22.1-alpine
    container_name: "proxy"
    volumes:
      # using env variables in nginx config
      - type: bind
        source: "./nginx/nginx.conf"
        target: "/etc/nginx/templates/default.conf.template"
      - type: bind
        source: "./nginx/cert"
        target: "/cert"
    networks:
      - internal
    ports:
      - "${EXTERNAL_PORT}:443"
    env_file:
      - .env
    depends_on:
      - home
      - issuer
      - redeemer

networks:
  internal:
    name: internal-network
    driver: bridge
